### PR TITLE
Update bench.lua and update results

### PR DESCRIPTION
**Pull request by andywingo**
* bench.lua: Update to use an inner loop more like pflua-match's inner
  loop.  We run for less time though because we collect more samples.

* bench.mk (ITERATIONS?): Lower to 20, because although we run for less
  time than pflua-match we still run at least 100ms per sample so there
  is less wild variance.

* deps/pflua: Update to master.

* results: Update.

### CODE REVIEW

**Comment by andywingo** [comment]
Updated again for new pflua and luajit, and re-ran benchmarks.

**Comment by kbara** [comment]
LGTM, though I'd like if repeated runs looked more similar; second-order variance seems to vary a fair amount. That said, it's not terrible:
ping-flood
ping-flood

**Comment by kbara** [comment]
(The above picture is to show reproducibility; for second-order variance, look at things like linux-bpf on the rightmost pflang expression)
wingolog org-2
wingolog org-2

**Comment by andywingo** [comment]
Interesting, thanks for taking time to test!

What are you pointing to with the linux-bpf comment?  I see lots of variablility for bpf-lua between the two images that you posted there, but not much for linux-bpf.  Did I miss something?  Can you be specific there?

**Comment by kbara** [comment]
Look at "net 178.79.151.0/24" for libpcap and linux-bpf. The height of the performance bars is basically the same, but the height of the variance/uncertainty line is drastically different, hence my comment about *second-order* variance.

**Comment by andywingo** [comment]
@kbara I see!  I would note however that the hairline represents the entire range of the data, so it doesn't represent variance in a statistical sense.  Perhaps I should figure out a way to overlay quartiles or multiples of the standard deviation or something.

**Comment by kbara** [comment]
Ahh, I've been misreading the convention behind the hairline the whole time. That said, it's still interesting that performance goes up/down so much for some configurations on some runs.

**Pull request merged**
